trigger:
  branches:
    include:
      - master

# not triggered by pull requests
# (these might come from a forked repo)
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- checkout: self
  clean: true
    # persistCredentials so we can push tags to the remote repo
  persistCredentials: true

- bash: |
    echo "##vso[task.setvariable variable=packageVersion]`cat package.json | jq .version -r`"
  displayName: extract version

- bash: |
    npm install
    npm run build
  displayName: 'npm install'

- bash: |
   npm run build
  displayName: 'npm build'

- bash: |
    npm run test
  displayName: 'npm test'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'hermeticarchitectureportal/hermetic'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(packageVersion)
      latest

- bash: |
    git config user.email pipeline@dev.azure.com
    git config user.name build-pipeline
    git tag -f $(packageVersion)
    git push -f --tags
  displayName: tag version

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MSDN Az Sub'
    appType: 'webAppContainer'
    WebAppName: 'hermetic'
    DockerNamespace: 'docker.io'
    DockerRepository: 'hermeticarchitectureportal/hermetic'
    DockerImageTag: '$(packageVersion)'